apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pipeline-sample
    newTag: latest
    
