apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: pipeline-sample   # ✅ Deployment의 label과 동일해야 함
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
